import re
from collections import defaultdict
from pathlib import Path
from typing import Any, Dict


class TestRegistryAnalyzer:
    r"""
    Analyze test generation results from a temporary directory.
    
    This class aggregates and categorizes test generation outcomes,
    including success rates, error distributions, and detailed attempt
    histories for each function. It provides methods to generate
    comprehensive reports at varying levels of verbosity.
    
    Parameters
    ----------
    tmp_dir : str | Path
        The directory path containing test generation artifacts.
    
    Attributes
    ----------
    tmp_dir : Path
        The resolved path to the temporary directory.
    summary : Dict[str, Any]
        A dictionary storing aggregated test results and statistics.
    
    Methods
    -------
    analyze :
        Process the temporary directory and compile test results.
    print_report :
        Display a formatted report of test results.
    
    Raises
    ------
    FileNotFoundError
        If the specified temporary directory does not exist.
    
    Warnings
    --------
    The analysis assumes a specific directory structure generated by the
    test generation pipeline. Manual intervention may be required for
    non-standard directory layouts.
    """

    def __init__(self, tmp_dir: str | Path):
        r"""
        Initialize the test generator with a temporary directory path.
        
        Creates a temporary directory for storing generated test files and
        initializes tracking metrics.
        
        Warnings
        --------
        Ensure the provided directory path exists and has write
        permissions.
        
        See Also
        --------
        pytest :
            The testing framework used to execute generated tests.
        
        Notes
        -----
        The temporary directory is converted to a Path object for
        cross-platform compatibility.
        """

        self.tmp_dir = Path(tmp_dir)
        self.summary = {
            "total_functions_scanned": 0,
            "successes": 0,
            "failures": 0,
            "error_distribution": defaultdict(int),
            "function_details": [],
        }

    def _extract_primary_error(self, content: str) -> str:
        r"""
        Extracts the primary error message from pytest execution output.
        
        Parses pytest execution output to isolate the first error message,
        truncating long lines and handling special cases like timeouts and
        syntax errors.
        
        Parameters
        ----------
        content : str
            The raw pytest execution output containing error messages.
        
        Returns
        -------
        str
            The primary error message, truncated to 120 characters if
            necessary.
        
            Special cases include 'Execution Timed Out', 'SyntaxError
            generated by LLM', and 'Unknown Error'.
        
        Raises
        ------
        AttributeError
            If the input content is not a string.
        """

        error_lines = re.findall("^E\\s+(.*)", content, re.MULTILINE)
        if error_lines:
            primary = error_lines[0].strip()
            return primary[:117] + "..." if len(primary) > 120 else primary
        elif "TimeoutExpired" in content or "TimeoutError" in content:
            return "Execution Timed Out (Infinite loop or hang)"
        elif "SyntaxError" in content:
            return "SyntaxError generated by LLM"
        else:
            return "Unknown Error (Check raw log manually)"

    def analyze(self) -> Dict[str, Any]:
        r"""
        Aggregates test execution metrics from the temporary directory.
        
        This method scans the temporary directory structure to compile a
        comprehensive summary of test execution results. It categorizes
        functions by success or failure, tracks the number of attempts
        used, and records the final error encountered if any. The summary
        includes a distribution of error types and detailed information for
        each function tested.
        
        Returns
        -------
        Dict[str, Any]
            A dictionary containing the aggregated test execution metrics.
            The dictionary includes:
        
            - `total_functions_scanned`: Total number of functions scanned.
            - `successes`: Number of functions that passed all tests.
            - `failures`: Number of functions that failed at least one
              test.
            - `error_distribution`: A dictionary mapping error categories
              to their counts.
            - `function_details`: A list of dictionaries, each containing
              details about a function, including its status, attempts
              used, final error, attempt history, and path.
        """

        if not self.tmp_dir.exists():
            return self.summary
        for module_dir in self.tmp_dir.iterdir():
            if not module_dir.is_dir():
                continue
            if module_dir.name == "__pycache__":
                continue
            for func_dir in module_dir.rglob("*"):
                if "__pycache__" in func_dir.parts:
                    continue
                if not func_dir.is_dir() or not any(func_dir.glob("attempt_*")):
                    continue
                self.summary["total_functions_scanned"] += 1
                is_success = bool(list(func_dir.glob("*_verified.py")))
                if is_success:
                    self.summary["successes"] += 1
                else:
                    self.summary["failures"] += 1
                attempt_history = []
                for log_file in sorted(func_dir.glob("attempt_*_pytest.log")):
                    match = re.search("attempt_(\\d+)_", log_file.name)
                    if match:
                        attempt_num = int(match.group(1))
                        err = self._extract_primary_error(
                            log_file.read_text(encoding="utf-8")
                        )
                        attempt_history.append({"attempt": attempt_num, "error": err})
                final_error = None
                if not is_success:
                    final_log = func_dir / "FINAL_FAILURE.log"
                    if final_log.exists():
                        final_error = self._extract_primary_error(
                            final_log.read_text(encoding="utf-8")
                        )
                        category = (
                            final_error.split(":")[0]
                            if ":" in final_error
                            else "Execution Failure"
                        )
                        self.summary["error_distribution"][category] += 1
                attempts_used = len(list(func_dir.glob("attempt_*_runnable.py")))
                self.summary["function_details"].append(
                    {
                        "function": func_dir.name,
                        "status": "success" if is_success else "fail",
                        "attempts_used": attempts_used,
                        "final_error": final_error,
                        "attempt_history": attempt_history,
                        "path": str(func_dir.relative_to(self.tmp_dir)),
                    }
                )
        self.summary["error_distribution"] = dict(self.summary["error_distribution"])
        self.summary["function_details"].sort(
            key=lambda x: (x["status"] == "success", x["function"])
        )
        return self.summary

    def print_report(self, verbosity: int = 0):
        r"""
        Print a formatted analysis report of test generation results.
        
        Generates a detailed report summarizing the test generation
        process, including success rates, error distributions, and failure
        breakdowns. The verbosity level controls the depth of the report.
        
        Parameters
        ----------
        verbosity : {'0', '1', '2'}, optional
            Controls the level of detail in the report. Default is 0.
        
        Returns
        -------
        None
            Prints the report to the console.
        """

        print("\n============================================================")
        print("                TEST REGISTRY ANALYSIS REPORT               ")
        print("============================================================")
        print(f"Total Functions Processed : {self.summary['total_functions_scanned']}")
        print(f"Successful Generations    : {self.summary['successes']}")
        print(f"Terminal Failures         : {self.summary['failures']}")
        if self.summary["total_functions_scanned"] > 0:
            success_rate = (
                self.summary["successes"]
                / self.summary["total_functions_scanned"]
                * 100
            )
            print(f"Success Rate              : {success_rate:.1f}%")
        print("\n--- Error Category Distribution ---")
        if not self.summary["error_distribution"]:
            print("  None detected.")
        else:
            for err_type, count in sorted(
                self.summary["error_distribution"].items(),
                key=lambda item: item[1],
                reverse=True,
            ):
                print(f"  - {err_type:<25}: {count}")
        if verbosity >= 1:
            print("\n--- Terminal Failures Breakdown ---")
            failures = [
                f for f in self.summary["function_details"] if f["status"] == "fail"
            ]
            if not failures:
                print("  No terminal failures.")
            for item in failures:
                print(
                    f"\n[FAIL] {item['function']} (Failed after {item['attempts_used']} attempts)"
                )
                print(f" └─> Final Error: {item['final_error']}")
                if verbosity >= 2:
                    print("     Attempt History:")
                    if not item["attempt_history"]:
                        print(
                            "       - No pytest logs found (syntax or import failure before execution)."
                        )
                    for att in item["attempt_history"]:
                        print(f"       - Try {att['attempt']}: {att['error']}")
                    print(f" └─> Path: {item['path']}")
        if verbosity >= 2:
            print("\n--- Successful Generations (Struggle Index) ---")
            successes = [
                f for f in self.summary["function_details"] if f["status"] == "success"
            ]
            if not successes:
                print("  No successes.")
            for item in successes:
                struggle = (
                    "One-Shot"
                    if item["attempts_used"] == 1
                    else f"Took {item['attempts_used']} attempts"
                )
                print(f"\n[OK] {item['function']} ({struggle})")
                if item["attempts_used"] > 1 and item["attempt_history"]:
                    for att in item["attempt_history"]:
                        print(f"     - Try {att['attempt']} failed: {att['error']}")
        print("\n============================================================\n")
